stages:
  - test
  - security
  - package
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA

# ------------------------------------------------------------------------------
# STAGE: TEST
# ------------------------------------------------------------------------------
unit-test-java:
  stage: test
  image: maven:3.9.6-eclipse-temurin-21-alpine
  cache:
    key: maven-cache
    paths:
      - .m2/repository/
  script:
    - mvn test -B -Dmaven.repo.local=.m2/repository

unit-test-frontend:
  stage: test
  image: node:20-alpine
  script:
    - npm ci
    - npm run build

# ------------------------------------------------------------------------------
# STAGE: SECURITY
# ------------------------------------------------------------------------------
container-scanning:
  stage: security
  image:
    name: aquasec/trivy:latest
    entrypoint: [""]
  script:
    - trivy fs --security-checks vuln,config --severity HIGH,CRITICAL .

# ------------------------------------------------------------------------------
# STAGE: PACKAGE
# ------------------------------------------------------------------------------
docker-build-push:
  stage: package
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  only:
    - main
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $IMAGE_TAG -f microservices/order-service/Dockerfile microservices
    - docker push $IMAGE_TAG

# ------------------------------------------------------------------------------
# STAGE: DEPLOY (GitOps Kubernetes)
# ------------------------------------------------------------------------------
k8s-deploy:
  stage: deploy
  image: bitnami/kubectl:latest
  only:
    - main
  script:
    - kubectl set image deployment/order-service-deployment order-service=$IMAGE_TAG -n logistics-prod
    - kubectl rollout status deployment/order-service-deployment -n logistics-prod
