apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: logistics-prod
  labels:
    app.kubernetes.io/name: kibana
    app.kubernetes.io/part-of: logistics-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana:8.12.2
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
          ports:
            - name: http
              containerPort: 5601
          env:
            - name: ELASTICSEARCH_HOSTS
              value: "http://elasticsearch.logistics-prod.svc.cluster.local:9200"
          readinessProbe:
            httpGet:
              path: /api/status
              port: 5601
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/status
              port: 5601
            initialDelaySeconds: 30
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: logistics-prod
  labels:
    app: kibana
spec:
  type: ClusterIP
  ports:
    - port: 5601
      name: http
      targetPort: 5601
  selector:
    app: kibana
