apiVersion: v1
kind: Secret
metadata:
  name: logistics-secrets
  namespace: logistics-prod
type: Opaque
stringData:
  DB_USERNAME: "logistics_admin"
  DB_PASSWORD: "ProdStrongPassword#2026"
  JWT_SECRET: "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef"
  REDIS_PASSWORD: "RedisSecureToken99"
